### ISSUE TITLE
Build a static website from the slides

### ISSUE THREAD

**Issue by zoosky** [kc/kc-serve#1]
Is this possible?

If yes, how?

**Comment by riezebosch** [comment]
Currently not.

**Comment by zoosky** [comment]
Thanks

**Comment by riezebosch** [comment]
My idea was to host it using kc-serve in a docker container.

**Comment by zoosky** [comment]
IMHO  static HTML is nice for distribution and simple secure deployment.

**Comment by riezebosch** [comment]
Yeah, but it also comes with a lot of overhead of package duplication or you should redirect (or at least have the option) to a CDN.
