### ISSUE TITLE
Idea: footer support

### ISSUE THREAD

**Issue by mthmulders** [kc/kc-serve#3]
It would be great if presentations could have a _footer_ - a small piece of markup to appear at the bottom of every slide. This is often done by having something like this:

    <div class="reveal">
      <div class="slides">
        
      </div>
      <div class="footer">
        <p>Copyright ©2018 MyCompany, Inc.</p>
      </div>
    </div>

Styling is - of course - done with CSS.

Ideally, the content of this footer should be something that can be changed at runtime. Maybe something like `kc serve --footer footer.html`.

What do you think about this idea?

**Comment by riezebosch** [comment]
If it's only about the copyright you can already fix it inside a custom template. Just like I did with the company logo. But still, your extension point is probably a good idea.

**Comment by mthmulders** [comment]
If by _custom template_ you meant _custom theme_, I wasn't able to achieve a footer with some text and an image by using only CSS styling.

If you mean everything that lives in `src/template`, I don't see how I could switch to another template?

Otherwise I'm a little confused what a template is...

But still, since you say it's a good idea, would you be willing to consider a PR?

**Comment by riezebosch** [comment]
Sure thing! I meant custom _theme_ but a custom _template_ was also crossing my mind as a proper solution.
